# Glue Visual ETL job to combine the catalog tables of reference and raw data
# Below code is generated by Glue Visual ETL job.

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from awsgluedq.transforms import EvaluateDataQuality

args = getResolvedOptions(sys.argv, ['JOB_NAME'])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

# Default ruleset used by all target nodes with data quality enabled
DEFAULT_DATA_QUALITY_RULESET = """
    Rules = [
        ColumnCount > 0
    ]
"""

# Script generated for node AWS Glue Data Catalog
AWSGlueDataCatalog_node1752359478404 = glueContext.create_dynamic_frame.from_catalog(database="db_youtube_cleaned", table_name="cleaned_statistics_ref_data", transformation_ctx="AWSGlueDataCatalog_node1752359478404")

# Script generated for node AWS Glue Data Catalog
AWSGlueDataCatalog_node1752359511600 = glueContext.create_dynamic_frame.from_catalog(database="db_youtube_cleaned", table_name="raw_data_transformed", transformation_ctx="AWSGlueDataCatalog_node1752359511600")

# Script generated for node Join
Join_node1752359557152 = Join.apply(frame1=AWSGlueDataCatalog_node1752359511600, frame2=AWSGlueDataCatalog_node1752359478404, keys1=["category_id"], keys2=["id"], transformation_ctx="Join_node1752359557152")

# Script generated for node Amazon S3
EvaluateDataQuality().process_rows(frame=Join_node1752359557152, ruleset=DEFAULT_DATA_QUALITY_RULESET, publishing_options={"dataQualityEvaluationContext": "EvaluateDataQuality_node1752359473144", "enableDataQualityResultsPublishing": True}, additional_options={"dataQualityResultsPublishing.strategy": "BEST_EFFORT", "observations.scope": "ALL"})
AmazonS3_node1752359652483 = glueContext.getSink(path="s3://youtube-analytics-useast1-315380538310-dev/combined_ref_raw/", connection_type="s3", updateBehavior="UPDATE_IN_DATABASE", partitionKeys=["region", "category_id"], enableUpdateCatalog=True, transformation_ctx="AmazonS3_node1752359652483")
AmazonS3_node1752359652483.setCatalogInfo(catalogDatabase="analytics",catalogTableName="combined_ref_raw_catalog")
AmazonS3_node1752359652483.setFormat("glueparquet", compression="snappy")
AmazonS3_node1752359652483.writeFrame(Join_node1752359557152)
job.commit()
