# Purpose - was to use Glue Visual ETL job to read partitioned catalog table of raw CSV data and apply data type transformations and write back to a new S3 bucket.
#  - but due to it's limitations with special data encodings I had to edit and try to make it work.
#  - but it didn't. 
# Below code template is generated by AWS Glue ETL Visual job with few force modifications in the script.

